version: '3.7'
services:
  db:
    container_name: homework_db
    image: "postgres:13-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  ingest:
    container_name: ingest-homework
    build:
      context: .
      args:
        TAXI_LINK: ${TAXI_LINK}
        ZONE_LINK: ${ZONE_LINK}
        TAXI_CSV: ${TAXI_CSV}
        ZONE_CSV: ${ZONE_CSV}
    depends_on:
      - db

volumes:
  postgres-data: null